version: '3.8'
services:
  mongo:
    image: mongo:6.0.5
    container_name: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=
      - MONGO_INITDB_ROOT_PASSWORD=
    restart: unless-stopped
    ports:
      - ":"
    volumes:
      - /:/data/db
    networks:
      - conkero-network
  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=
      - ME_CONFIG_MONGODB_ADMINPASSWORD=
      - ME_CONFIG_MONGODB_URL=mongodb://:@mongo:/?authSource=admin
      - ME_CONFIG_BASICAUTH_USERNAME=
      - ME_CONFIG_BASICAUTH_PASSWORD=
    links:
      - mongo
    restart: unless-stopped
    ports:
      - ":"
    networks:
      - conkero-network
networks:
  conkero-network:
    external: true