version: '3.8'
services:
  mongo:
    image: mongo:6.0.5
    container_name: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=12345678
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - /:/data/db
    networks:
      - conkero-network
  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=12345678
      - ME_CONFIG_MONGODB_URL=mongodb://root:12345678@mongo:27017/?authSource=admin
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=12345678
    links:
      - mongo
    restart: unless-stopped
    ports:
      - "8081:8081"
    networks:
      - conkero-network
networks:
  conkero-network:
    external: true